In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1)

## a) Add together these vectors mod 2, u = v + b

v = {1,0,0,1,0,1,1,0}

b = {1,1,0,0,1,1,0,0}

In [2]:
v = np.array([1,0,0,1,0,1,1,0])
b = np.array([1,1,0,0,1,1,0,0])
u = v + b
u.shape

(8,)

In [5]:
u = np.mod(u, 2 * np.ones(8))
print(u)

[0. 1. 0. 1. 1. 0. 1. 0.]


## b)  Add together u + b   

In [7]:
s = np.mod(u + b, 2 * np.ones(8))
print(s)

[1. 0. 0. 1. 0. 1. 1. 0.]


## c)  Is the answer to (1b) the same as v? 

In [8]:
v == s

array([ True,  True,  True,  True,  True,  True,  True,  True])

Yes **s**, answer to **(1b)**, and **v** are the same. Above represents an array of True/False values depending on whether each individual element w/in vector was the same. Since it returned a vector of all Trues, we know that **v** & **s** are the same.

## d)  Given v = w + b  solve for w

In [13]:
w = u.copy()
print('Vector w: {}'.format(w))
print("Vector w + b with this vector: {}".format(np.mod(w + b, 2 * np.ones(8))))
print("Vector v: {}".format(v))

Vector w: [0. 1. 0. 1. 1. 0. 1. 0.]
Vector w + b with this vector: [1. 0. 0. 1. 0. 1. 1. 0.]
Vector v: [1 0 0 1 0 1 1 0]


As you can see, vector **w** is the same as vector **u** as seen above. Also shown above is that v is reproduced with **w = u**. 

# 2) 

## a) Find the linear recurrence which generated this sequence:

{1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 
1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 
0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0}

In [16]:
seq = np.array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0])
print(seq)

[1 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1
 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1
 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0
 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0]


In [75]:
def mtrx_generator(A, rec_size, full=False):
    if not full:                       # used to calculate square matrices for linear solve below
        gen = []
        for i in range(rec_size):
            gen.append(A[i:rec_size+i])
        return np.array(gen)
    else:                             # used to calculate the full matrix to see if recurrence solution is correct
        gen = []
        for i in range(len(A)-rec_size):
            gen.append(A[i:rec_size+i])
        return np.array(gen)
def target_generator(A,rec_size=0, full=False):
    if not full:                      # used to calculate appropriate target vector for linear solve below
        return A[rec_size:2*rec_size]
    else:                             # used to calculate the full target to see if recurrence solution is correct
        return A[rec_size:]

In [76]:
for i in range(2,64): # 64 => max number of recurrences produceable with square matrices in our linear solve
    A = mtrx_generator(seq,i)
    b = target_generator(seq, i)
    try:
        x = np.linalg.solve(A,b)
        print('Recurrence Length {} has solution {}'.format(i,x))
    except:
        print('Issue with recurrence length: {}'.format(i))
    

Recurrence Length 2 has solution [1. 0.]
Issue with recurrence length: 3
Issue with recurrence length: 4
Recurrence Length 5 has solution [ 1.  1.  0. -1. -1.]
Recurrence Length 6 has solution [-1. -1.  0.  2.  1.  1.]
Issue with recurrence length: 7
Recurrence Length 8 has solution [-1.  0.  0.  3. -1.  2. -3.  2.]
Recurrence Length 9 has solution [ 5.00000000e-01  1.00000000e+00  0.00000000e+00  5.00000000e-01
 -5.00000000e-01 -1.11022302e-16 -5.00000000e-01 -1.48029737e-16
  5.00000000e-01]
Recurrence Length 10 has solution [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00 -1.00000000e+00
  1.00000000e+00 -1.00000000e+00  1.00000000e+00 -1.00000000e+00
  8.32667268e-17  1.00000000e+00]
Recurrence Length 11 has solution [ 0.00000000e+00 -4.00000000e+00  1.80143985e+16 -1.80143985e+16
  1.80143985e+16 -1.80143985e+16  1.80143985e+16 -1.80143985e+16
  1.50000000e+00  1.80143985e+16 -1.80143985e+16]
Recurrence Length 12 has solution [-1. -2.  3. -2.  3. -2.  3. -2. -2.  4. -1. -1.]
Recur

By above, we can check with the recurrence length iterations that actually produced a result. Hence, we will check if the solution actually works for Recurrence length 2, 5, 6,...

**Checking for Recurrence Length 2**

In [84]:
A = mtrx_generator(seq, 2, full=True)
b = target_generator(seq,2,full=True)
rec_x = np.array([1,0])
print(np.mod(A.dot(rec_x),2) == b)

[ True  True  True  True False False  True False False False  True  True
 False False  True  True  True False False False  True False  True False
 False False False False False  True False False  True False  True  True
  True False  True  True  True  True False  True False False  True  True
 False  True False  True False  True  True False  True  True False False
 False False  True  True  True  True  True False False  True False False
 False  True  True False False  True  True  True False False False  True
 False  True False False False False False False  True False False  True
 False  True  True  True False  True  True  True  True False  True False
 False  True  True False  True False  True False  True  True False  True
  True False False False False  True]


As seen above, the recurrence of length 2 clearly has insufficient lag terms to describe this pattern, hence we have false terms present in our comparision array (which does element-by-element comparision).

**Checking for Recurrence Length 5**

In [85]:
A = mtrx_generator(seq, 5, full=True)
b = target_generator(seq,5,full=True)
rec_x = np.array([1.,1.,  0., -1., -1])
print(np.mod(A.dot(rec_x),2) == b)

[ True  True  True  True  True False False  True False False False  True
  True False False  True  True  True False False False  True False  True
 False False False False False False  True False False  True False  True
  True  True False  True  True  True  True False  True False False  True
  True False  True False  True False  True  True False  True  True False
 False False False  True  True  True  True  True False False  True False
 False False  True  True False False  True  True  True False False False
  True False  True False False False False False False  True False False
  True False  True  True  True False  True  True  True  True False  True
 False False  True  True False  True False  True False  True  True False
  True  True False]


As seen above, the recurrence of length 5 clearly has insufficient lag terms to describe this pattern, hence we have false terms present in our comparision array (which does element-by-element comparision).

**Checking for Recurrence Length 6**

In [86]:
A = mtrx_generator(seq, 6, full=True)
b = target_generator(seq,6,full=True)
rec_x = np.array([-1., -1.,  0.,  2.,  1.,  1.])
print(np.mod(A.dot(rec_x),2) == b)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]


As we can see above, **Recurrence with length 6** fits our pattern perfectly. Hence, the linear recurrence for our pattern is:

$x_n = x_{n-1} + x_{n-2} + 2 * x_{n-3} - x_{n-5} - x_{n-6}$

## b) what is its period?

The period, given our perfect recurrence with **length 6**, of this sequence is (given P = period)

$P = 2^n-1 = 2^6 - 1 = 63$

Hence the **period is 63**.