In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# For the game with payoff matrix X (the data is below)  the payoffs are given from the perspective of the row player. (1)

In [33]:
X = np.array([[4, -3, 1, 3, 6, 2], [5, 9, 3, 9, -5, 5], [3, 8, 3, 5, 7, -7], [-9, 9, 7, 3, 2, 4], [9, 4, 8, -1, 1, 1], [2, 4, -2, 2, 5, 9]])
print(X.shape)
print(X)

(6, 6)
[[ 4 -3  1  3  6  2]
 [ 5  9  3  9 -5  5]
 [ 3  8  3  5  7 -7]
 [-9  9  7  3  2  4]
 [ 9  4  8 -1  1  1]
 [ 2  4 -2  2  5  9]]


## Check to see if there are any rows or columns that are dominated and can be removed.  Iterate to remove as many as possible. (a)

There does not seem to exist any dominated rows/cols. Every row/col is doing better in at least on entry compared to every other row/col hence, no decision/choice can be removed out right because its payoffs are dominated by other choices.

## Find the game's expectation.  Does this game favor the row player or the column player? (b)

In [34]:
solu = np.linalg.solve(X.T, np.ones(6))
print(solu)

[0.11885846 0.04373951 0.01708339 0.04346948 0.06119001 0.04756682]


In [35]:
print('Expectation of the Game is {}'.format(1/np.sum(solu)))

Expectation of the Game is 3.012886069395837


Because the expectation of the Game was **positive**, this game favours the row player.

## Find the probability for options A, B, C, D, E, F which will guarantee the row player's results meet the game's expectation in the long run. (c)

In [36]:
prob_row_vec = solu/np.sum(solu)
options = ['A', 'B', 'C', 'D', 'E', 'F']
for i in range(len(options)):
    print('Probability for Option {}: {}'.format(options[i], prob_row_vec[i]))

Probability for Option A: 0.3581069950546809
Probability for Option B: 0.1317821639048858
Probability for Option C: 0.051470316318880605
Probability for Option D: 0.13096858999573044
Probability for Option E: 0.18435853731513885
Probability for Option F: 0.14331339741068333


## Find the probability for options A, B, C, D, E, F which will guarantee the column player's results meet the game's expectation in the long run. (d) RELOOK

In [37]:
solu1 = np.linalg.solve(X.T, np.ones(6))
prob_col_vec = solu1/np.sum(solu1)
options = ['A', 'B', 'C', 'D', 'E', 'F']
for i in range(len(options)):
    print('Probability for Option {}: {}'.format(options[i], prob_col_vec[i]))

Probability for Option A: 0.3581069950546809
Probability for Option B: 0.1317821639048858
Probability for Option C: 0.051470316318880605
Probability for Option D: 0.13096858999573044
Probability for Option E: 0.18435853731513885
Probability for Option F: 0.14331339741068333


# For the game with payoff matrix Y (the data is below)  the payoffs are given from the perspective of the row player. (2)

In [40]:
Y = np.array([[1, 8, 8, 6, 3, 8], [5, 5, 8, 9, 9, 9], [3, 3, 3, 4, 8, 7], [0, 2, 3, 3, 2, 5], [7, 9, 4, 4, 6, 4], [5, 0, 3, 5, 7, 1]])
print(Y.shape)
print(Y)

(6, 6)
[[1 8 8 6 3 8]
 [5 5 8 9 9 9]
 [3 3 3 4 8 7]
 [0 2 3 3 2 5]
 [7 9 4 4 6 4]
 [5 0 3 5 7 1]]


## Check to see if there are any rows or columns that are dominated and can be removed.  Iterate to remove as many as possible. (a)

***First Set of Row Deletions:*** The rows that are dominated with Y in its current form.
1. Row 3 dominated by Row 2
2. Row 4 dominated by Row 2
3. Row 6 dominated by Row 2


In [41]:
Y = np.delete(Y, 2, axis=0) # 3rd row deletion as it is dominated by 2nd row
Y = np.delete(Y, 2, axis=0) # "4th" row deletion (technically indices fall after the first deletion, 
                            # so 4th row is considered in the new Y after the first deletion as the 3rd row)
Y = np.delete(Y, 3, axis=0) # "6th" row deletion
print(Y.shape)
print(Y)

(3, 6)
[[1 8 8 6 3 8]
 [5 5 8 9 9 9]
 [7 9 4 4 6 4]]


***First Set of Column Deletions:*** The columns that are dominated with the Y **above** are
1. Column 2 (dominated by Column 1)
2. Column 6 (dominated by Column 3)

In [42]:
Y = np.delete(Y, 1, axis=1)
Y = np.delete(Y, 4, axis=1)
print(Y.shape)
print(Y)

(3, 4)
[[1 8 6 3]
 [5 8 9 9]
 [7 4 4 6]]


***Second Set of Row Deletions:*** The rows that are dominated with the Y **above** are
1. Row 1 (dominated by Row 2)

In [43]:
Y = np.delete(Y, 0, axis=0)
print(Y.shape)
print(Y)

(2, 4)
[[5 8 9 9]
 [7 4 4 6]]


***Second Set of Column Deletions:*** The columns that are dominated with the Y **above** are
1. Column 3 (dominated by Column 2)
2. Column 4 (dominated by Column 2)

In [44]:
Y = np.delete(Y, 2, axis=1)
Y = np.delete(Y, 2, axis=1)
print(Y.shape)
print(Y)

(2, 2)
[[5 8]
 [7 4]]


The rows in the matrix above correspond to **row 2** and **row 5**

The columns in the matrix above correspond to **col 1** and **col 3**

## Find the game's expectation.  Does this game favor the row player or the column player? (b)

In [45]:
solu2b = np.linalg.solve(Y.T, np.ones(2))
print('Expectation of the Game is {}'.format(1/np.sum(solu2b)))

Expectation of the Game is 5.999999999999999


Because the expectation is greater than 0, this game clearly favours the **row player**

## Find the probability for options A, B, C, D, E, F which will guarantee the row player's results meet the game's expectation in the long run. (c)

In [46]:
prv = solu2b/np.sum(solu2b)
results = [(0,'A'), (prv[0], 'B'), (0,'C'), (0,'D'), (prv[1], 'E'), (0,'F')]
for val, let in results:
    print('Probability for Option {}: {}'.format(let, val))

Probability for Option A: 0
Probability for Option B: 0.5
Probability for Option C: 0
Probability for Option D: 0
Probability for Option E: 0.49999999999999994
Probability for Option F: 0


## Find the probability for options A, B, C, D, E, F which will guarantee the column player's results meet the game's expectation in the long run. (d)

In [47]:
solu2d = np.linalg.solve(Y, np.ones(2))
pcv = solu2d/np.sum(solu2d)
results = [(pcv[0],'A'), (0, 'B'), (pcv[1],'C'), (0,'D'), (0, 'E'), (0,'F')]
for val, let in results:
    print('Probability for Option {}: {}'.format(let, val))

Probability for Option A: 0.6666666666666666
Probability for Option B: 0
Probability for Option C: 0.3333333333333335
Probability for Option D: 0
Probability for Option E: 0
Probability for Option F: 0


# For the game with payoff matrix Z (the data is below) .  The payoffs are given from the perspective of the row player. (3)

In [50]:
Z = np.array([[9, 8, 1], [6, 7, 7], [8, 8, 2]])
print(Z.shape)
print(Z)

(3, 3)
[[9 8 1]
 [6 7 7]
 [8 8 2]]


## Check to see if there are any rows or columns that are dominated and can be removed.  Iterate to remove as many as possible. (a)

By looking at the matrix above, no row is dominated by another row, hence we immediately move to column elimination. 

In column elimination, we can get rid of **col 2** as it is **dominated by col 3**. 

In [51]:
Z = np.delete(Z, 1, axis=1)
print(Z.shape)
print(Z)

(3, 2)
[[9 1]
 [6 7]
 [8 2]]


With this new Z matrix, there are **no row eliminations** that we can conduct because no row dominates another row.

## Find the game's expectation.  Does this game favor the row player or the column player? (b)

Given the fact that we have boundary cases present here, we need to test 3 sets of cases: when the row player **does not consider option A**, when the row player **does not consider option B**, and finally similarly for **option C**.

In [56]:
# w/o option A Expectation
optA = Z[1:]
soluA = np.linalg.solve(optA.T, np.ones(2))
print('Expectation (without row player considering option A) of the Game is {}'.format(1/np.sum(soluA)))

Expectation (without row player considering option A) of the Game is 6.285714285714285


In [57]:
# w/o option B expectation
optB = np.array([Z[0], Z[2]])
soluB = np.linalg.solve(optB.T, np.ones(2))
print('Expectation (without row player considering option B) of the Game is {}'.format(1/np.sum(soluB)))

Expectation (without row player considering option B) of the Game is 5.000000000000001


In [59]:
# w/o option C expectation
optC = Z[:2]
soluC = np.linalg.solve(optC.T, np.ones(2))
print('Expectation (without row player considering option C) of the Game is {}'.format(1/np.sum(soluC)))

Expectation (without row player considering option C) of the Game is 6.333333333333334


In all the above cases, where the row player ignored a certain option in favour of 2 other options, the row player was expected to win. Thereby, because in all cases the row player was expected to win, overall the game favours **the row player**.

## Find the probability for options A, B, C which will guarantee the row player's results meet the game's expectation in the long run. (c)

Because the row player is choosing a **mixed strategy**, we know that the row player will only consider the set of options that provides them the highest expectation. Since above, the set of options that **omit C** have the highest expected pay out, the row player will then **only choose** between **options A & B**. 

Thereby, we can consider the probability of option C to be 0.

In [60]:
prv = soluC/np.sum(soluC)
print('Probability for Option {}: {}'.format('A', prv[0]))
print('Probability for Option {}: {}'.format('B', prv[1]))
print('Probability for Option {}: {}'.format('C', 0))

Probability for Option A: 0.11111111111111116
Probability for Option B: 0.8888888888888888
Probability for Option C: 0


##  Find the probability for options A, B, C which will guarantee the column player's results meet the game's expectation in the long run. (d)



Because we know that the row player will **omit option C** from their deliberations, and we know that the column player has a dominant strategy present leading to the middle column being eliminated earlier, we know then that only the ***soluC*** matrix will be used to calculate their long run decisions. 

In [61]:
optC = Z[:2]
soluC = np.linalg.solve(optC, np.ones(2))
prc = soluC/np.sum(soluC)
print('Probability for Option {}: {}'.format('A', prc[0]))
print('Probability for Option {}: {}'.format('B', 0))
print('Probability for Option {}: {}'.format('C', prc[1]))

Probability for Option A: 0.6666666666666666
Probability for Option B: 0
Probability for Option C: 0.3333333333333334


# General Comments

***Name:*** Yashaswi Sharma

***UID:*** 116245821

With each section below, I have labelled what question it comes from. For example, the first section is has a "(1)" appended to it, signifying that this section is for question 1.